---
name: Unix-Shebang
version: 0.314
author:
  - 'Ask Solem <asksh@cpan.org>'
abstract: Utility module for Unix shebang lines.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Spec: 0
  Getopt::Long: 0
  IO::File: 0
build_requires:
  Test::More: 0.42
dynamic_config: 0
provides:
  Unix::Shebang:
    file: lib/Unix/Shebang.pm
    version: 0.314
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
